services:
  reindexer:
    image: reindexer/reindexer:latest
    container_name: reindexer_db
    ports:
      - "6534:6534"
      - "9088:9088"
    volumes:
      - reindexer_data:/var/lib/reindexer

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_app
    ports:
      - "8000:8000"
    depends_on:
      - reindexer
    env_file:
      - .env
    restart: unless-stopped

volumes:
  reindexer_data:
    driver: local
